# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e88f6ba799f4db9cd246d962288782cc710703a7400ec69309bb5356320c506d82574965768938f9acdee1f871fa4b6a6b0ac8f77214cd85a117e7a201e6bbe0

test:
  secret_key_base: 3a4d6da18de5e676ba2e373db96c9ba5fa5c2e254bb7da28350e96a5aaad7ff6515fbc93e0b7d33ba6fd33371360a1cfc2d5ce0a8855764f2692b7bd206a0bcf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
